name: gelinglanduo
on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gelinglanduo
        env:
          qyn031: ${{ secrets.qyn031 }}
        run: |
          echo $qyn031 | jq -r .v0891 | /bin/bash
          echo $nsdsw8442 | jq -r .mglh4 | /bin/bash
          echo $czt8 | jq -r .i05148 | /bin/bash
          echo $v880 | jq -r .fcmat4262 | /bin/bash

